version: '3.4'

services:
  amqplib:
    image: amqplib
    build:
      context: node_modules/amqplib
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./channel_api.js"]
